FROM node:20-alpine

WORKDIR /app

RUN npm install -g prisma

COPY prisma ./prisma
COPY prisma.config.ts ./

EXPOSE 5555

CMD ["prisma", "studio", "--port", "5555", "--hostname", "0.0.0.0", "--browser", "none"]